# Generated by Django 4.1.2 on 2022-10-18 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudainte',
            new_name='Estudiante',
        ),
    ]
